### ISSUE TITLE
'driveScope' appears not enough to upload file

### ISSUE THREAD

**Issue by kChaikaSnap31** [brendanhay/gogol#107]
This code 

```
uploadFile :: Text -> IO ()
uploadFile path = do
    lgr <- newLogger Debug stdout
    env <- newEnv <&> (envLogger .~ lgr) . (envScopes .~ driveScope)

    body <- sourceBody "upload.png"

    runResourceT . runGoogle env $ do
        _ <- upload filesCreate body
        liftIO $ print "Upload completed"
```

raises an error

Couldn't match type ‘Network.Google.Auth.Scope.HasScope'
                             '["https://www.googleapis.com/auth/drive"]
                             (Scopes (MediaUpload (File -> FilesCreate)))’
                     with ‘'True’
        arising from a use of ‘upload’

Why is that?

**Comment by gbordyugov** [comment]
https://github.com/brendanhay/gogol/issues/98 - does this one look similar?

**Comment by kChaikaSnap31** [comment]
Actually i've forgot to create a File with smart constructor. So I'll close it.
