### ISSUE TITLE
Gogol and Amazonka Project Status Update

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/gogol#110]
Hi folks,

I just wanted to share an update about the status of open issues for both [amazonka](https://github.com/brendanhay/amazonka) and [gogol](https://github.com/brendanhay/gogol).

Since both projects have been lagging behind with regards to issue resolution and Hackage/Stackage releases, I will be spending the end of August and early September working full-time on both projects to get everything back in shape and the reported bugs ironed out, as well as adding support for any new APIs.

Thanks for your patience!

Related: brendanhay/amazonka#484

**Comment by fsoikin** [comment]
Is there a plan for LTS 12, and if so, what is it? 

I see there are a few breaking changes in the libraries, so you probably can't keep the same source for all supported resolvers? Or can you?

I was going to offer some help with it, but realized I don't understand the strategy regarding resolvers.

**Comment by d12frosted** [comment]
Hi @brendanhay,

First of all, thank you for all these libraries! ✨ 

Secondly, are there any updates? 😸 If you need any help in the upgrade process, just let me know.

**Comment by brendanhay** [comment]
The `0.4.0` release is now available on Hackage. Many thanks to @MichaelXavier and the other contributors for getting this out the door!
