### ISSUE TITLE
Prepare 0.4.0 release

### ISSUE THREAD

**Issue by MichaelXavier** [brendanhay/gogol#121]
@brendanhay I just pushed a change to develop that bumped everything to 0.4.0. This was primarily so that folks that are vendoring pre-release gogol can do things like CPP against the package version. It looks like there's only one changelog for the whole project that references the version tag and mentions new libraries and service definitions. I think I can probably write that changelog. Beyond that, do you just call `stack upload`, or is there any other administrivia I'm missing? I suspect you're probably strapped for time so I want to try to just get this done to have something released. Let me know.

**Comment by brendanhay** [comment]
Thanks for preparing everything @MichaelXavier, the `0.4.0` release is now available on Hackage. :+1:
