### ISSUE TITLE
Google Ads API

### ISSUE THREAD

**Issue by JuanGalilea** [brendanhay/gogol#130]
Is there a way to get the new Google Ads API included here?

I've read the issue about adwords but since the have changed the inner workings of the API maybe its possible now?

I couldn't find it in the google service discovery list but maybe i'm doing it wrong

**Comment by brendanhay** [comment]
You can find the (periodically) synched list of  available definitions from service discovery here: https://github.com/brendanhay/gogol/tree/main/configs/models

If the model you want to generate bindings for exists, then a configuration needs to be added to: https://github.com/brendanhay/gogol/tree/main/configs/services. You can check the [README](https://github.com/brendanhay/gogol#adding-new-services) for a minimal example.

Unfortunately at first glance I don't think the Ads API is actually part of service discovery and is provided as separate bespoke libraries, such as the [Python](https://developers.google.com/google-ads/api/docs/client-libs/python/) client library.
