### ISSUE TITLE
gogol-photoslibrary went missing

### ISSUE THREAD

**Issue by huppmann** [brendanhay/gogol#141]
PR #129 commit 5c1cafa487c4 whacked the file gen/model/photoslibrary/v1/photoslibrary-api.json

https://github.com/brendanhay/gogol/pull/129/commits/5c1cafa487c4f86002ba8aed48f89e36eb3b65b2#diff-f7a044b1f59872642f01972205ec2a8f

Please don't think i'm expecting anybody to be able to bring it back, unless it was just some glitch in somebody downloading the API descriptions that somebody can, pretty please, rectify. (I myself have no idea; hence why there's no PR here. i'd just try adding

https://photoslibrary.googleapis.com/$discovery/rest?version=v1

but i have no idea if that's the right thing to do)

Thanks for considering

cc: @kim

**Comment by kim** [comment]
Interesting. All the generated code here is based on the official Go API client, which is in turn based on https://www.googleapis.com/discovery/v1/apis. The photoslibrary API apparently got pulled from there: https://github.com/googleapis/google-api-go-client/issues/368

**Comment by huppmann** [comment]
thanks for the explanation, @kim. i figured it must've been something like that (that i didn't know how to track down myself)

i followed your issue link and left [this comment](https://github.com/googleapis/google-api-go-client/issues/368#issuecomment-545189597) there

seems like there's nothing more for you gogol hackers to do so i'll close

again, thanks for looking into it
