### ISSUE TITLE
New major release

### ISSUE THREAD

**Issue by AlistairB** [brendanhay/gogol#154]
Hi,

I would be interested in doing / assisting in a new major release with regenerated libraries. https://github.com/brendanhay/gogol/issues/152#issuecomment-678257351 mentions some work is underway. Is it possible to assist with this?

https://github.com/brendanhay/gogol/pull/153 is some initial work I have done. I have used this to regenerate (excluding `videointelligence` to avoid the last issue). My immediate use case is I want to use [secret manager](https://cloud.google.com/secret-manager) which is working fine from [my fork](https://github.com/AlistairB/gogol/tree/my-fork).

**Comment by gwils** [comment]
@brendanhay Any word on this?

**Comment by brendanhay** [comment]
@gwils I'm fully booked trying to get a large `amazonka` release out. Once that's done I'll do the gogol one.

**Comment by shinzui** [comment]
Friendly ping that the hackage release is still broken. It would be really nice to let others help with this project since Haskell developers are increasingly using GCP.

**Comment by TomMD** [comment]
On this note - is there interest/will on your part Brendan in setting up a gogol github organization and having a few maintainers?

**Comment by shinzui** [comment]
@TomMD See #166

**Comment by thomasbach-dev** [comment]
Yes please! I think its really important, that in the Haskell ecosystem

**Comment by brendanhay** [comment]
I'm in the process of porting all the `amazonka` build, CI, and generator changes to `gogol`, now that the former's 2.0 release is ready.

**Comment by tonicebrian** [comment]
Any way we could help on this? Without GCP support I'll have to drop Haskell from our Stack.

**Comment by tonicebrian** [comment]
Hi, I'm helping @brendanhay in getting Gogol in shape. And I will put some hours now or then. Just ping me here with issues and/or PRs and  I will try to address them ASAP. Closing for now.
