### ISSUE TITLE
Upgrade to new Servant versions

### ISSUE THREAD

**Issue by danwdart** [brendanhay/gogol#156]
Trying to compile gogol-core 0.5.0 currently errors with the following:

```
[6 of 6] Compiling Network.Google.Prelude ( src/Network/Google/Prelude.hs, dist/build/Network/Google/Prelude.o )

src/Network/Google/Prelude.hs:31:1: error:
    Could not find module ‘Servant.Utils.Links’
    Use -v to see a list of the files searched for.
   |
31 | import Servant.Utils.Links as Export hiding (Link)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is because Servant has removed that file, but gogol-core has no upper bound on its version restriction.

Workaround for now: Restrict servant to < 0.17 because Servant.Utils.Links no longer exists in 0.17.

**Comment by AlistairB** [comment]
Hi, this has been fixed in master but not released. I don't think @brendanhay has time for maintaining this library at the moment. I am working around the issue by loading `gogol` via git. See https://github.com/brendanhay/gogol/issues/147#issuecomment-635735272

**Comment by danwdart** [comment]
Ah, thanks!

**Comment by yaitskov** [comment]
me too ;)
