### ISSUE TITLE
Add myself as maintainer

### ISSUE THREAD

**Issue by AlistairB** [brendanhay/gogol#166]
Hi,

I'd be interested in assisting with maintenance of this project. I don't have a huge amount of time available, but I would be interested in getting a new release out + assisting with curating PRs and issues.

Cheers

**Comment by shinzui** [comment]
It would be great to have more contributors to gogol. @brendanhay could you please consider expanding the maintainers?

**Comment by AlistairB** [comment]
Unfortunately my time has diminished further. Going to close this cheers.
