### ISSUE TITLE
Support for error handling with response body?

### ISSUE THREAD

**Issue by mkscrg** [brendanhay/gogol#18]
`gogol` doesn't offer much context for API errors right now, since it uses [`checkStatus`](https://github.com/brendanhay/gogol/blob/4592e14ab7d931bb0d87ac7a8b83790437900aa5/gogol/src/Network/Google/Internal/HTTP.hs#L83) to throw `ServiceError` on non-success response statuses. (And `checkStatus` doesn't have access to the response body.)

Is this intentional, or a planned change in the future? It's hard to work with these APIs without any error context beyond the raw status code.

These libraries (`amazonka` etc) are amazing btw :+1::grinning::wrench:

**Comment by mkscrg** [comment]
To illustrate, here's a change we're playing with to get more error context: https://github.com/brendanhay/gogol/compare/brendanhay:4592e14...wagonhq:f889ed9

**Comment by brendanhay** [comment]
Definitely open to improving anything that makes your lives easier. If you don't mind, I'll lift most of your code and integrate it.
