### ISSUE TITLE
How are new Scopes managed in `envScopes`

### ISSUE THREAD

**Issue by tonicebrian** [brendanhay/gogol#181]
Following recommendations from https://github.com/brendanhay/gogol/issues/147#issuecomment-635735272 I'm using latest commit on master to have `gogol` in my project. But then all the scope code changed and instead of having `storageReadWriteScope` like being used in the examples https://github.com/brendanhay/gogol/blob/main/examples/src/Example/Storage.hs#L46 now we have `Devstorage'ReadWrite`. When trying to use the new symbol I get this compilation error:

    Data constructor not in scope:
      Devstorage'ReadWrite :: Proxy scopes0

Can we have an updated example with the new Scope symbols?

**Comment by nathankot** [comment]
I am revisiting/updating some old Haskell code and got things compiling with:

```haskell
storageReadWrite :: Proxy '[Storage.Devstorage'ReadWrite]
storageReadWrite = Proxy

allow storageReadWrite someExistingCredentials
```
