### ISSUE TITLE
gogol-core-0.0.1 does not compile

### ISSUE THREAD

**Issue by peti** [brendanhay/gogol#21]
Citing from http://hydra.cryp.to/build/1732331/nixlog/1/raw:

~~~
Building gogol-core-0.0.1...
Preprocessing library gogol-core-0.0.1...

src/Network/Google/Data/Time.hs:37:18:
    Could not find module ‘Servant.Common.Text’
    Use -v to see a list of the files searched for.
~~~~

I suppose that module has been removed from servant-0.6.x?

**Comment by brendanhay** [comment]
Thanks for notifying me. I'll look at upgrading it to whatever the replacement is.

**Comment by traytonwhite** [comment]
Other option could be to add a `< 0.5` upper bound to the servant build-depends in `core/gogol-core.cabal` file. Not sure if that would work for NixOS, though.

Relevant servant change log here: https://github.com/haskell-servant/servant/blob/master/servant-server/CHANGELOG.md#05

**Comment by peti** [comment]
Yes, you should definitely [edit your Cabal file on Hackage](http://hackage.haskell.org/package/gogol-core/maintain) to add that constraint on `servant`. It won't help NixOS, though, because we have updated our version of `servant` already and cannot easily compile the package with an older version any more.

**Comment by brendanhay** [comment]
A fix has been pushed for future releases, and the [cabal metadata](http://hackage.haskell.org/package/gogol-core-0.0.1/gogol-core.cabal) was updated.
