### ISSUE TITLE
Request: Support contacts (People API)

### ISSUE THREAD

**Issue by alhirzel** [brendanhay/gogol#24]
Hey, thank you for creating this library! I was wondering if you could wrap the People API, i.e. Google Contacts? The Google Discovery Service link is here:

https://developers.google.com/apis-explorer/#p/people/v1/

**Comment by brendanhay** [comment]
`gogol-people` has [already been created](https://github.com/brendanhay/gogol/tree/develop/gogol-people), but won't be available on Hackage until the next release, in hopefully a week or two.
