### ISSUE TITLE
`Byte` should be base64Url encoded `ByteString` not `Word8`

### ISSUE THREAD

**Issue by amarpotghan** [brendanhay/gogol#26]
First of all thanks for your excellent work. I noticed this problem while I was trying to use gmail-api. `mraw` should be base64Url encoded ByteString instead of a Word8. Google description here: https://developers.google.com/discovery/v1/type-format . I think other gogol-* libraries affected as well by this.

**Comment by brendanhay** [comment]
Thanks for raising the issue, it effect multiple libraries as you mention. I'll look into it!

**Comment by amarpotghan** [comment]
Thank you for quick response :)

**Comment by MaxDaten** [comment]
```
-- | Image content, represented as a stream of bytes.
gogol-vision Network.Google.Vision.iContent :: Lens' Image (Maybe Word8)
```
https://github.com/brendanhay/gogol/blob/25813b5e25c571a0fae1ae2530870d0c3507f11e/gogol-vision/gen/Network/Google/Vision/Types/Product.hs#L308

is also affected

**Comment by brendanhay** [comment]
The generation code has been updated to select a new internal representation for `bytes` types. This representation now handles transparent encoding/decoding of Base64URL encoding, and changes the external lens interface to accept a plain (unencoded) `ByteString`. See PR #29 for specifics.
