### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by k-bx** [brendanhay/gogol#28]
Hi!

I would really appreciate a new hackage release of all libs, would help using gogol with latest GHC and servant.

Thank you!

**Comment by brendanhay** [comment]
The last hurdle for a `0.2` release is documenting the new typed OAuth scopes and some improvements to the existing documentation in `gogol` regarding usage.

**Comment by k-bx** [comment]
👍  thank you!

**Comment by brendanhay** [comment]
The `0.1.0` release is going through stackage approval now, if that's your thing. If successful it should in the nightly snapshot sometime this week.
