### ISSUE TITLE
Documentation on how the generation works

### ISSUE THREAD

**Issue by aristidb** [brendanhay/gogol#4]
I'm curious about how the generation works, and I suspect so might be other people. Does it use this?: https://developers.google.com/discovery/

**Comment by brendanhay** [comment]
Yeah, the models are copied directly from the official go sdk, which in turn is just downloading/vendoring the discovery service documents: https://github.com/brendanhay/gogol/tree/develop/gen/model.

I can write up some actual documentation about the generation process if it's useful for some particular reason, but I suspect it's probably not that interesting and at the current stage is going to be subject to changes over the next few weeks.

**Comment by aristidb** [comment]
I guess it could streamline the generation process to switch to the Discovery API rather than the Go SDK, I bet it's the same JSON format anyways...?

Then, you could even put the generation in the Makefile, complete with updating. "make regenerate" :)

**Comment by brendanhay** [comment]
The format the Go SDK uses is identical (to the remote discovery service endpoints), they are simply crawling/copying the documents and then vendoring them locally, before parsing them for the generation step. I'd assume something similar here - since the vendoring of the models is quite nice if only for the `git diff` to see when subtle things have changed.

**Comment by brendanhay** [comment]
As it stands `cd gen; make full-clean; make` will wipe the local models, re-vendor the Go SDK's JSON service descriptions, and then regenerate/format all of the libraries.

**Comment by aristidb** [comment]
Ah OK, missed that.

**Comment by brendanhay** [comment]
I'll close this for now, in favour of a more general 'document all the things', as well as probably moving to a all-in-Haskell generation step at some point in the future.
