### ISSUE TITLE
Please update gogol-datastore to v1

### ISSUE THREAD

**Issue by runeksvendsen** [brendanhay/gogol#42]
Hi there

There's a final version of the Datastore API out, v1: https://cloud.google.com/datastore/docs/reference/rest/#collection-v1projects

Will you update gogol-datastore to support this version?

Thank you.

**Comment by brendanhay** [comment]
Sure, I'll look at regenerating all the libraries.

**Comment by brendanhay** [comment]
The `develop` branch now has the updated `gogol-datastore` code. The documentation is as usual available [here](http://brendanhay.nz/gogol-doc/gogol-datastore/index.html). I'll release this when the other libraries have been built and tested on CI.

**Comment by runeksvendsen** [comment]
First of all: thanks!

I've now had a chance to try out the library, and everything works as promised. I've tested by starting with a non-transactional insert of an Entity, followed by a repeated number of `beginTransaction -> lookup -> commit update/rollback` transactions, and everything works like a charm.

Side note: I get around 75 milliseconds average latency for a single of the above transaction type (comprising three requests).

**Comment by brendanhay** [comment]
Great! That's good to know @runeksvendsen, thanks for sharing your findings. When the [build](https://travis-ci.org/brendanhay/gogol/builds/172870650) for [Release 0.1.1](https://github.com/brendanhay/gogol/pull/44) successfully goes through, I'll upload the updated packages to Hackage.

**Comment by brendanhay** [comment]
The updated [gogol-datastore](http://hackage.haskell.org/package/gogol-datastore) supporting V1 of the API is now available on Hackage.

**Comment by runeksvendsen** [comment]
Wonderful! Thanks again.
