### ISSUE TITLE
Firebase Cloud Messaging support

### ISSUE THREAD

**Issue by dhess** [brendanhay/gogol#43]
Thanks for this wonderful package. Any plans to support FCM?

**Comment by brendanhay** [comment]
A requirement is the [Google Discovery API] must expose the service definition for FCM. Currently it seems it's not supported by the [other SDKs](https://developers.google.com/discovery/libraries) either.

**Comment by dhess** [comment]
Yeah, that's what I was afraid you'd say :) Oh well, maybe it'll show up there in the future. Thanks!
