### ISSUE TITLE
Installed application credentials are inadequate.

### ISSUE THREAD

**Issue by sopvop** [brendanhay/gogol#46]
Unless I'm missing something, the `InstalledApplication` credentials can only handle the initial authorization, and does not allow to store refresh token or use refresh token to authenticate.

The "Installed application" flow should be something like

* if have refresh token - use it to initialize store, otherwise do the authorization token dance and get refresh/access token.
* Run your app, which refreshes access token if needed
* Store the refresh token since it could have been changed when refreshing.

So currently missing building blocks would be

```haskell
data Credentials s = FromRefreshToken RefereshToken
                | ...
retrieveStoredAuth :: MonadIO m => Store s -> m (Auth s)
```

And installed app usage would be like
```haskell
initialiseCreds :: OAuthClient -> Logger -> Manager -> IO (Credentials s)
initialiseCreds client logger manager = do
    refreshToken <- readSavedToken
    case refreshToken of
      Just t -> pure (FromRefreshToken t)
      Nothing -> do
          T.putStrLn (formUrl ...)
          code <- OAuthCode <$> T.getLine
          pure (FromClient client code)

main = do
    logger <- newLogger
    manager <- newManager
    creds <- initializeCreds client logger manager
    env <- newEnvWith ....
    runApp
    auth <- retreiveStoreAuth (env^.envStore)
    saveRefreshToken auth
```

On top of that we can build something more like a google python api does - let users store this auth information in a json file before program exists, and try to read it same way as `ServiceAccount` or `AuthorizedUser` does.
```javascript
{ "client_id" : "..."
, "client_secret" : "..."
, "access_token" : ".."
, "token_expiration" : "2016-12-01T..."
, "refresh_token" : "..."
}
```

For all use cases google recommends storing refresh tokens and reusing them, so this may be useful not only for "Installed application" case.

What do you think?

**Comment by brendanhay** [comment]
Hi @sopvop, everything you said makes perfect sense! I'll look at creating a basic PR shortly, let me know if you're available to help testing and I'll keep you updated.

**Comment by sopvop** [comment]
I don't think I'll be able to work on for next two weeks, but I may help reviewing patch.

**Comment by rueshyna** [comment]
@brendanhay, @sopvop can you review it?

Based on @sopvop idea, I added several functions to save/refresh FromClient-constructed Credentials. 

https://github.com/brendanhay/gogol/pull/66

**Comment by sopvop** [comment]
Looks right, thanks
