### ISSUE TITLE
OOMs from fresh build

### ISSUE THREAD

**Issue by gambogi** [brendanhay/gogol#5]
When doing a clean stack build:
```
gogol-datastore-0.0.1: install
gogol-dataflow-0.0.1: install
Progress: 102/158
--  While building package gogol-compute-0.0.1 using:
      /home/gambogi/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build lib:gogol-compute --ghc-options  -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/gambogi/projects/gogol/.stack-work/logs/gogol-compute-0.0.1.log

    Configuring gogol-compute-0.0.1...
    Preprocessing library gogol-compute-0.0.1...
    [  1 of 194] Compiling Network.Google.Compute.Types.Sum ( gen/Network/Google/Compute/Types/Sum.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Network/Google/Compute/Types/Sum.o )
    [  2 of 194] Compiling Network.Google.Compute.Types.Product ( gen/Network/Google/Compute/Types/Product.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Network/Google/Compute/Types/Product.o )
    ghc: out of memory (requested 1048576 bytes)
```

Not sure if this is primarily a gogol, stack, cabal, or ghc issue, but I figured I'd start here.

**Comment by brendanhay** [comment]
This is being built on a 3.7 GB Travis instance (AWS) as well as locally on an 8 GB linux laptop - with the one caveat that it is being done serially. I'm not entirely sure from the output, but it looks like a potentially concurrent build of many of the libraries? Can you share your machine specs and if you are in fact running a global make for the entire project or a selective subset?

**Comment by gambogi** [comment]
I was building on an `Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz` (/proc/cpu/info)
8GB ram. I was definitely running a full build. I think stack may have been automatically parallelizing builds, which may have caused the issue. I'll try forcing a serial build and see if that fixes it. (It probably will)

**Comment by brendanhay** [comment]
I'll close this for now, feel free to reopen and add more information if you're still having issues.
