### ISSUE TITLE
Wrong type for Gogol.BigQuery.jclQuote

### ISSUE THREAD

**Issue by lorenzo** [brendanhay/gogol#52]
[The jclQuote lens](http://brendanhay.nz/gogol-doc/gogol-bigquery/Network-Google-BigQuery.html#v:jclQuote) should actually be optional. Currently it is a required text, but it should have been `Maybe Text`.

The consequence of the current implementation is that it is impossible to process a JSON payload without getting an error about this field. The error is:

`Only CSV imports may specify a quote character`

Setting `jclQuote` to an empty Text has no effect on the error.

**Comment by brendanhay** [comment]
That's rather unfortunate, the specification gives it a default value of `\"`. I'll add an override to make it optional and regenerate `gogol-bigquery`.

**Comment by brendanhay** [comment]
Fixed in 83f0555, which is now in `develop`.
