### ISSUE TITLE
request to publish changes

### ISSUE THREAD

**Issue by rueshyna** [brendanhay/gogol#71]
@brendanhay Could you publish new changes?
I really need this change, https://github.com/brendanhay/gogol/pull/66.

Thanks!

**Comment by rueshyna** [comment]
@brendanhay Could you?

**Comment by brendanhay** [comment]
Apologies for the overdue reply. I'm currently in the process of upgrading the generator's build dependencies and will try to get out a minor release with your changes on the weekend.

**Comment by rueshyna** [comment]
@brendanhay  looking forward to new publish :)

**Comment by mbj** [comment]
@rueshyna Its in progress here https://github.com/brendanhay/gogol/pull/72

**Comment by rueshyna** [comment]
I saw the changes were released, thank you! @brendanhay

**Comment by brendanhay** [comment]
Apologies for the delays, @rueshyna, and thanks for your patience.

**Comment by tonicebrian** [comment]
See https://github.com/brendanhay/gogol/issues/154#issuecomment-2469880391
