### ISSUE TITLE
AdWords API

### ISSUE THREAD

**Issue by richardfergie** [brendanhay/gogol#8]
Is there an easy way to get the AdWords API included in this?

I think it is a little different to the other Google APIs so maybe it is not possible to use the same approach.

**Comment by brendanhay** [comment]
Unfortunately if it's not showing up in the [Google Discovery Service](https://developers.google.com/apis-explorer/#p/discovery/v1/discovery.apis.list) list, then as you mentioned it is not going to be compatible with the current approach. If there is in fact some kind of machine readable service definition/specification describing the API I'm happy to support the additional format.

**Comment by richardfergie** [comment]
Seems like this is a problem for a few different library developers (e.g. https://github.com/google/google-api-nodejs-client/issues/267)

I don't know enough about this to be sure, but I don't think there is a machine readable service description.
