### ISSUE TITLE
Google Sheets - Developer Metadata API

### ISSUE THREAD

**Issue by saurabhnanda** [brendanhay/gogol#89]
Is the [Google Sheets - Developer metadata API](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.developerMetadata) supported by Gogol? I tried searching at https://www.stackage.org/lts-9.0/hoogle?q=metadata&package=gogol-sheets - but the results seems to be about some _other_ metadata, not _developer_ metadata.

**Comment by korayal** [comment]
It is supported on the latest release: http://hackage.haskell.org/package/gogol-sheets
