### ISSUE TITLE
Regenerate DFAReporting API package

### ISSUE THREAD

**Issue by SPY** [brendanhay/gogol#91]
Hi.
Current version of generated DFAReporting API is v2.7. It was deprecated about half an year ago. Current supported version is 3.0(previous 2.8 is obsolete already too). Is it possible to regenerate bindings? Should I do it myself and make pull request with new version?

**Comment by korayal** [comment]
Should be available on the latest release 0.4.0

**Comment by MichaelXavier** [comment]
Yep, looks like we can resolve this: https://hackage.haskell.org/package/gogol-dfareporting
