### ISSUE TITLE
Running into basic HasScope type error

### ISSUE THREAD

**Issue by cah6** [brendanhay/gogol#98]
Hello all, 

I'm running into a type error when trying to execute a request with the gogol.bigquery library. My code is:
```
runRequest :: TableDataInsertAllRequest -> IO (Rs TableDataInsertAllRequest)
runRequest req = do
  manager <- newManager defaultManagerSettings
  logger  <- newLogger Debug stdout
  creds <- getApplicationDefault manager
  env <- newEnv <&> (envLogger .~ logger) . (envScopes .~ bigQueryScope ! bigQueryInsertDataScope ! cloudPlatformScope)
  -- env  <- newEnvWith creds logger manager <&> envScopes .~ (bigQueryScope ! bigQueryInsertDataScope ! cloudPlatformScope)
  runResourceT . runGoogle env $ send req
```
with the intention that it'll pick up my config file at `~.config/gcloud/application_default_credentials.json`. It's giving the type error: 
```
error:
    • Couldn't match type ‘Network.Google.Auth.Scope.HasScope'
                             '["https://www.googleapis.com/auth/bigquery",
                               "https://www.googleapis.com/auth/bigquery.insertdata",
                               "https://www.googleapis.com/auth/cloud-platform"]
                             (Scopes TableDataInsertAllRequest)’
                     with ‘'True’
        arising from a use of ‘send’
    • In the second argument of ‘($)’, namely ‘send req’
      In a stmt of a 'do' block: runResourceT . runGoogle env $ send req
      In the expression:
        do manager <- newManager defaultManagerSettings
           logger <- newLogger Debug stdout
           creds <- getApplicationDefault manager
           env <- newEnv
                    <&>
                      (envLogger .~ logger)
                        . (envScopes
                             .~ bigQueryScope ! bigQueryInsertDataScope ! cloudPlatformScope)
           ....
   |
77 |   runResourceT . runGoogle env $ send req
   |                                  ^^^^^^^^
```
I know I must be missing something fairly obvious, but I'm also having a hard time wrapping my head around how this whole HasScope / type family works with lenses. Any help would be appreciated!

**Comment by gbordyugov** [comment]
I remember having exactly the same error due to two nearly identical request names `projectList/projectsList`. What type does your `req` have?

**Comment by cah6** [comment]
`req` has the type `TableDataInsertAllRequest`, and I made it using the smart constructor in https://hackage.haskell.org/package/gogol-bigquery-0.3.0/docs/Network-Google-BigQuery-Types.html#t:TableDataInsertAllRequest. It's possible I have the wrong name somewhere but I'm not sure what it would be?

**Comment by gbordyugov** [comment]
https://github.com/brendanhay/gogol/blob/develop/gogol-bigquery/gen/Network/Google/Resource/BigQuery/TableData/InsertAll.hs#L120 — that's the type/instance you must be looking for

https://github.com/brendanhay/gogol/blob/develop/gogol-bigquery/gen/Network/Google/Resource/BigQuery/TableData/InsertAll.hs#L84 — and the corresponding smart c'tor

**Comment by cah6** [comment]
Oh, psh yeah that works! I actually did have code to go from `TableDataInsertAllRequest -> TableDataInsertAll` (the latter represents a request on a specific table / dataset) but forgot to use it instead of the `*Request`. Thank you so much for the quick responses!
